table dim_location
	lineageTag: ac80cb8a-51df-40e9-8b25-43c829d067ad

	column Location_SK
		dataType: int64
		formatString: 0
		lineageTag: 6b7c7dc7-edc8-4fd7-8a81-2bb476ed04f9
		summarizeBy: none
		sourceColumn: Location_SK

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 1fa0fb4d-0a21-481e-872c-168758973a66
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column StateProvinceName
		dataType: string
		lineageTag: 35ad690e-ab7e-4113-bb52-90e321fa24e4
		summarizeBy: none
		sourceColumn: StateProvinceName

		annotation SummarizationSetBy = Automatic

	column CountryName
		dataType: string
		lineageTag: 299dfc19-e5b5-486e-8900-9c4b4fb03d25
		summarizeBy: none
		sourceColumn: CountryName

		annotation SummarizationSetBy = Automatic

	column SpatialLocation
		dataType: string
		lineageTag: a13683c1-da08-4913-9734-193c2baded77
		summarizeBy: none
		sourceColumn: SpatialLocation

		annotation SummarizationSetBy = Automatic

	hierarchy 'CountryName Hierarchy'
		lineageTag: 4030f580-34db-4abf-ac92-5377c3c72cab

		level CountryName
			lineageTag: 73d9e26d-bf82-4db5-b715-e2b87c3f8631
			column: CountryName

		level StateProvinceName
			lineageTag: 6350ff1c-28b9-4037-8122-c79d2bb3eff5
			column: StateProvinceName

		level City
			lineageTag: 8fdeae42-ac52-45ea-906c-600df0b948ca
			column: City

	partition dim_location = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-980023092254454.14.azuredatabricks.net", "/sql/1.0/warehouses/f8b7002c9488e388", [Catalog = "", Database = ""]),
				    adventure_works_catalog_Database = Source{[Name="adventure_works_catalog",Kind="Database"]}[Data],
				    silver_Schema = adventure_works_catalog_Database{[Name="silver",Kind="Schema"]}[Data],
				    dim_location_Table = silver_Schema{[Name="dim_location",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dim_location_Table,{"AddressID", "AddressLine1", "AddressLine2", "PostalCode"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

