table dim_product
	lineageTag: 0a7f06f5-36ce-430e-b6ca-42fba3d7ec2c

	column Product_SK
		dataType: int64
		formatString: 0
		lineageTag: a5a2f870-3a83-4271-a500-e6cfcb4bb32c
		summarizeBy: none
		sourceColumn: Product_SK

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: a5accb73-4572-45d4-8094-a6ea66b0016f
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ProductCategory
		dataType: string
		lineageTag: 8d4085af-81c8-4005-aa4b-967a29fdcf18
		summarizeBy: none
		sourceColumn: ProductCategory

		annotation SummarizationSetBy = Automatic

	column ProductSubCategoy
		dataType: string
		lineageTag: c97a486f-7aaa-4a26-9fc4-a22b502e8bb4
		summarizeBy: none
		sourceColumn: ProductSubCategoy

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 0b09f5ff-66a0-40a5-8a28-def58bebd8de
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = User

	column StandardCost
		dataType: double
		lineageTag: 15e1ae9d-f631-41b4-a472-73b69a69a5ae
		summarizeBy: none
		sourceColumn: StandardCost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy 'ProductName Hierarchy'
		lineageTag: a589208b-dea5-4e0e-ae9e-e107f8d281ce

		level ProductCategory
			lineageTag: 911bcad4-514f-499b-b4ec-af5994aaf928
			column: ProductCategory

		level ProductSubCategoy
			lineageTag: c1cde91c-8f2f-4798-9552-539b8ae5425c
			column: ProductSubCategoy

		level ProductName
			lineageTag: ed280a13-fbeb-4888-bcd9-2f3000e951f6
			column: ProductName

	partition dim_product = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-980023092254454.14.azuredatabricks.net", "/sql/1.0/warehouses/f8b7002c9488e388", [Catalog = "", Database = ""]),
				    adventure_works_catalog_Database = Source{[Name="adventure_works_catalog",Kind="Database"]}[Data],
				    silver_Schema = adventure_works_catalog_Database{[Name="silver",Kind="Schema"]}[Data],
				    dim_product_Table = silver_Schema{[Name="dim_product",Kind="Table"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(dim_product_Table,null,"Miscellaneous",Replacer.ReplaceValue,{"Category", "SubCategory"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value", "ProductCategory", each if [Category] = "Not registered" and [SubCategory] = "Not registered" then "Miscellaneous" else [Category]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "ProductSubCategoy", each if [Category] = "Not registered" and [SubCategory] = "Not registered" then "Miscellaneous" else [SubCategory]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"Category", "SubCategory", "ModelName", "ListPrice"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

