table SpatialLocation
	lineageTag: 615b5924-cdb2-419a-8a29-3e66194bc75a

	column Latitude
		dataType: double
		lineageTag: b96f9a64-4272-4079-be1d-2f62ecc39e56
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: d033e93c-1da9-4771-8a41-4b5baa0b232b
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SpatialLocation = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(Databricks.Catalogs("adb-3073418945021346.6.azuredatabricks.net", "/sql/1.0/warehouses/ba136deae61fb922", [Catalog="adventure_works_catalog", Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]){[Name="adventure_works_catalog",Kind="Database"]}[Data], "SELECT#(lf)    DISTINCT#(lf)    split(#(lf)        regexp_replace(SpatialLocationString, 'POINT \\(|\\)', ''), #(lf)        ' '#(lf)    )[1] AS Latitude,#(lf)    split(#(lf)        regexp_replace(SpatialLocationString, 'POINT \\(|\\)', ''), #(lf)        ' '#(lf)    )[0] AS Longitude#(lf)FROM adventure_works_catalog.bronze.person_address", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Latitude", type number}, {"Longitude", type number}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

