# Databricks notebook source
# MAGIC %md
# MAGIC # Dimensional Model – Dimensions
# MAGIC
# MAGIC Notebook responsável pela criação das **dimensões analíticas** do modelo dimensional (Adventure Works)
# MAGIC
# MAGIC Inclui dimensões com **chaves substitutas** e documentação no Unity Catalog.

# COMMAND ----------

import sys
sys.path.append("..")

# COMMAND ----------

#Imports e setup

from pyspark.sql import functions as F
from pyspark.sql import SparkSession
from pyspark.sql.functions import xxhash64
from datetime import datetime
from ADB.Module.GovernanceUtils import audit_registration, get_run_id, silver_selection
from ADB.Module.SilverUtils import (
    deduplicate_by_rule,
    add_column_comments,
    write_silver
)

# COMMAND ----------

current_run_id = get_run_id()

# Leitura das tabelas Silver (clean)
df_customer        = spark.table("adventure_works_catalog.silver.clean_sales_customer")
df_sales_territory = spark.table("adventure_works_catalog.silver.clean_sales_territory")
df_sales           = spark.table("adventure_works_catalog.silver.clean_sales_order_header")
df_person          = spark.table("adventure_works_catalog.silver.clean_person")
df_store           = spark.table("adventure_works_catalog.silver.clean_sales_store")
df_inventory       = spark.table("adventure_works_catalog.silver.clean_production_inventory")
df_person_address  = spark.table("adventure_works_catalog.silver.clean_person_address")
df_vendor          = spark.table("adventure_works_catalog.silver.clean_purchasing_vendor")
df_product         = spark.table("adventure_works_catalog.silver.clean_production")
df_currency        = spark.table("adventure_works_catalog.silver.clean_sales_currency")
df_currency_rate   = spark.table("adventure_works_catalog.silver.clean_sales_currency_rate")

# COMMAND ----------

# =====================================================
# DIM_CUSTOMER - SILVER
# =====================================================
start_time = datetime.now()

# Granularidade: 1 linha por cliente (pessoa ou loja)

# Criando a tabela
spark.sql("""
CREATE TABLE IF NOT EXISTS adventure_works_catalog.silver.dim_customer (
    Customer_SK BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CustomerID INT,
    PersonID INT,
    StoreID INT,
    CustomerType STRING,
    PersonName STRING,
    StoreName STRING
)
""")

# Registro para dados nulos
spark.sql("""
INSERT INTO adventure_works_catalog.silver.dim_customer
SELECT
    -1 AS Customer_SK,
    -1 AS CustomerID,
    NULL AS PersonID,
    NULL AS StoreID,
    'NOT REGISTERED' AS CustomerType,
    'Not registered' AS PersonName,
    'Not registered' AS StoreName
WHERE NOT EXISTS (
    SELECT 1
    FROM adventure_works_catalog.silver.dim_customer
    WHERE CustomerID = -1
);
""")

# Preparação dos dados
df_dim_customer_base = (
    df_customer.alias("c")

    .join(
        df_person.alias("p"),
        F.col("c.PersonID") == F.col("p.PersonID"),
        "left"
    )

    .join(
        df_store.alias("s"),
        F.col("c.StoreID") == F.col("s.StoreID"),
        "left"
    )

    .select(
     
        # Chave Natural
        F.col("c.CustomerID").alias("CustomerID"),

         # Identificação 
         F.col("c.PersonID").alias("PersonID"),
         F.col("c.StoreID").alias("StoreID"),

        # Tipo de cliente
        F.when(F.col("c.PersonID").isNotNull(), F.lit("PERSON"))
         .when(F.col("c.StoreID").isNotNull(),  F.lit("STORE"))
         .otherwise(F.lit("NOT REGISTERED"))
         .alias("CustomerType"),

        # Nome da pessoa
        F.when(
            F.col("c.PersonID").isNotNull(),
            F.concat_ws(" ", F.col("p.FirstName"), F.col("p.LastName"))
        ).otherwise(F.lit("Not registered"))
         .alias("PersonName"),

        # Nome da loja
        F.when(
            F.col("c.StoreID").isNotNull(),
            F.col("s.StoreName")
        ).otherwise(F.lit("Not registered"))
         .alias("StoreName")
    )
)

# Garantia de Integridade 
df_dim_customer_base = (
    df_dim_customer_base
    .filter(F.col("CustomerID").isNotNull())
)

full_table_name = "adventure_works_catalog.silver.dim_customer"
table_name_short = "dim_customer"

try:
    df_dim_customer_base = deduplicate_by_rule(
        df_dim_customer_base,
        partition_cols=["CustomerID"],
        order_cols=[
            F.col("PersonID").isNotNull().desc(),
            F.col("StoreID").isNotNull().desc()
        ]
    )

    df_dim_customer_base.cache()

    #Registros processados após as regras e joins (volume transformado)
    rows_processed = df_dim_customer_base.count()

    silver_selection(
        spark=spark,
        run_id=current_run_id,
        df_input=df_dim_currency_base,
        process_name="Criação_dim_table",
        table_name=table_name_short
    )

    # Merge SCD Type 1
    df_dim_customer_base.createOrReplaceTempView("src_dim_customer")

    spark.sql("""
    MERGE INTO adventure_works_catalog.silver.dim_customer tgt
    USING src_dim_customer src
    ON tgt.CustomerID = src.CustomerID

    WHEN MATCHED AND (
        NOT (tgt.PersonID     <=> src.PersonID) OR
        NOT (tgt.StoreID      <=> src.StoreID) OR
        NOT (tgt.CustomerType <=> src.CustomerType) OR
        NOT (tgt.PersonName   <=> src.PersonName) OR
        NOT (tgt.StoreName    <=> src.StoreName)
    )
    THEN UPDATE SET
        tgt.PersonID     = src.PersonID,
        tgt.StoreID      = src.StoreID,
        tgt.CustomerType = src.CustomerType,
        tgt.PersonName   = src.PersonName,
        tgt.StoreName    = src.StoreName

    WHEN NOT MATCHED THEN
    INSERT (
        CustomerID,
        PersonID,
        StoreID,
        CustomerType,
        PersonName,
        StoreName
    )
    VALUES (
        src.CustomerID,
        src.PersonID,
        src.StoreID,
        src.CustomerType,
        src.PersonName,
        src.StoreName
    )
    """)

    #Pegar métricas do merge do DESCRIBE_HISTORY
    merge_metrics = (
        spark.sql(f"DESCRIBE HISTORY {full_table_name}")
        .orderBy(F.col("version").desc())
        .limit(1)
        .select("operationMetrics")
        .collect()[0]["operationMetrics"]
    )

    rows_written = (
        int(merge_metrics.get("numTargetRowsInserted", 0))
        + int(merge_metrics.get("numTargetRowsUpdated", 0))
    )

    audit_registration(
        spark=spark,
        run_id=current_run_id,
        process_name="Criação_dim_table",
        layer="SILVER",
        table_saved = table_name_short,
        start_date = start_time,
        rows_readed_batch = rows_processed,
        rows_written_batch = rows_written
    )

    df_dim_customer_base.unpersist()

except Exception as e:

    df_dim_customer_base.unpersist()
    
    audit_registration(
        spark=spark,
        run_id=current_run_id,
        process_name="Criação_dim_table",
        layer="SILVER",
        table_saved = table_name_short,
        start_date = start_time,
        status = "FAIL",
        error_msg = str(e)
    )

    print(f"Erro em dim_customer: {e}")


# Descrição das colunas
dim_customer_columns = {
    "Customer_SK": "Chave substituta do cliente",
    "CustomerID": "Identificador natural do cliente",
    "PersonID": "Identificador da pessoa física (NULL para lojas)",
    "StoreID": "Identificador da loja (NULL para pessoas físicas)",
    "CustomerType": "Tipo de cliente: PERSON ou STORE",
    "PersonName": "Nome do cliente quando pessoa física",
    "StoreName": "Nome do cliente quando pessoa jurídica"
}

# Adicionando os comentários no Unity Catalog
add_column_comments(
    catalog="adventure_works_catalog",
    schema="silver",
    table="dim_customer",
    columns_dict=dim_customer_columns
)

