# Databricks notebook source
# MAGIC %md
# MAGIC # Dimensional Model – Dimensions
# MAGIC
# MAGIC Notebook responsável pela criação das **dimensões analíticas** do modelo dimensional (Adventure Works)
# MAGIC
# MAGIC Inclui dimensões com **chaves substitutas** e documentação no Unity Catalog.

# COMMAND ----------

import sys
sys.path.append("..")

# COMMAND ----------

#Imports e setup

from pyspark.sql import functions as F
from pyspark.sql import SparkSession
from pyspark.sql.functions import xxhash64
from datetime import datetime
from ADB.Module.SilverUtils import (
    deduplicate_by_rule,
    add_column_comments,
    write_silver,
)

# COMMAND ----------

# Leitura das tabelas Silver (clean)
df_customer        = spark.table("adventure_works_catalog.silver.clean_sales_customer")
df_sales_territory = spark.table("adventure_works_catalog.silver.clean_sales_territory")
df_sales           = spark.table("adventure_works_catalog.silver.clean_sales_order_header")
df_person          = spark.table("adventure_works_catalog.silver.clean_person")
df_store           = spark.table("adventure_works_catalog.silver.clean_sales_store")
df_inventory       = spark.table("adventure_works_catalog.silver.clean_production_inventory")
df_person_address  = spark.table("adventure_works_catalog.silver.clean_person_address")
df_vendor          = spark.table("adventure_works_catalog.silver.clean_purchasing_vendor")
df_product         = spark.table("adventure_works_catalog.silver.clean_production")
df_currency        = spark.table("adventure_works_catalog.silver.clean_sales_currency")
df_currency_rate   = spark.table("adventure_works_catalog.silver.clean_sales_currency_rate")

# COMMAND ----------

# ============================================================
# DIM_PRODUCT — SILVER 
# ============================================================
# Granularidade: 1 linha por produto 

# Criando a tabela
spark.sql("""
CREATE TABLE IF NOT EXISTS adventure_works_catalog.silver.dim_product (
    Product_SK BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ProductID INT,
    ProductName STRING,
    Category STRING,
    SubCategory STRING,
    ModelName STRING,
    StandardCost DECIMAL(18,2),
    ListPrice DECIMAL(18,2)
)
""")

# Registro para dados nulos
spark.sql("""INSERT INTO adventure_works_catalog.silver.dim_product
SELECT
    -1 AS Product_SK,
    -1 AS ProductID,
    'Not registered',
    'Not registered',
    'Not registered',
    'Not registered',
    0,
    0
WHERE NOT EXISTS (
    SELECT 1
    FROM adventure_works_catalog.silver.dim_product
    WHERE ProductID = -1
);
""")

#Preparação dos dados
df_dim_product_base = (
    df_product
    .select(
        F.col("ProductID"),

        F.coalesce(F.col("ProductName"), F.lit("Not registered")).alias("ProductName"),
        F.coalesce(F.col("ProductCategoryName"), F.lit("Not registered")).alias("Category"),
        F.coalesce(F.col("ProductSubcategoryName"), F.lit("Not registered")).alias("SubCategory"),
        F.coalesce(F.col("ProductModelName"), F.lit("Not registered")).alias("ModelName"),

        F.col("StandardCost"),
        F.col("ListPrice")
    )

)

# Garantia de integridade
df_dim_product_base = deduplicate_by_rule(
    df_dim_product_base,
    partition_cols=["ProductID"],
    order_cols=[
        F.col("ProductName").isNotNull().desc(),
        F.col("StandardCost").isNotNull().desc(),
        F.col("ListPrice").isNotNull().desc()
    ]
)

# View de origem
df_dim_product_base.createOrReplaceTempView("src_dim_product")

# Merge SCD type 1
spark.sql("""
MERGE INTO adventure_works_catalog.silver.dim_product tgt
USING src_dim_product src
ON tgt.ProductID = src.ProductID

WHEN MATCHED AND (
    NOT (tgt.ProductName  <=> src.ProductName) OR
    NOT (tgt.Category     <=> src.Category) OR
    NOT (tgt.SubCategory  <=> src.SubCategory) OR
    NOT (tgt.ModelName    <=> src.ModelName) OR
    NOT (tgt.StandardCost <=> src.StandardCost) OR
    NOT (tgt.ListPrice    <=> src.ListPrice)
)
THEN UPDATE SET 
    tgt.ProductName  = src.ProductName,
    tgt.Category     = src.Category,
    tgt.SubCategory  = src.SubCategory,
    tgt.ModelName    = src.ModelName,
    tgt.StandardCost = src.StandardCost,
    tgt.ListPrice    = src.ListPrice

WHEN NOT MATCHED THEN
  INSERT (
    ProductID,
    ProductName,
    Category,
    SubCategory,
    ModelName,
    StandardCost,
    ListPrice
  )
  VALUES (
    src.ProductID,
    src.ProductName,
    src.Category,
    src.SubCategory,
    src.ModelName,
    src.StandardCost,
    src.ListPrice
  )
""")

# Documentação das colunas
dim_product_columns = {
    "Product_SK": "Chave substituta gerada automaticamente (coluna identity)",
    "ProductID": "Chave natural do produto",
    "ProductName": "Nome do produto",
    "Category": "Categoria do produto",
    "SubCategory": "Subcategoria do produto",
    "ModelName": "Modelo do produto",
    "StandardCost": "Custo padrão do produto",
    "ListPrice": "Preço de lista do produto"
}


# Adicionando os comentários no Unity Catalog
add_column_comments(
    catalog="adventure_works_catalog",
    schema="silver",
    table="dim_product",
    columns_dict=dim_product_columns
)
