# Databricks notebook source
# MAGIC %md
# MAGIC # Dimensional Model – Dimensions
# MAGIC
# MAGIC Notebook responsável pela criação das **dimensões analíticas** do modelo dimensional (Adventure Works)
# MAGIC
# MAGIC Inclui dimensões com **chaves substitutas** e documentação no Unity Catalog.

# COMMAND ----------

import sys
sys.path.append("..")

# COMMAND ----------

#Imports e setup

from pyspark.sql import functions as F
from pyspark.sql import SparkSession
from pyspark.sql.functions import xxhash64
from datetime import datetime
from ADB.Module.GovernanceUtils import audit_registration, get_run_id, silver_selection
from ADB.Module.SilverUtils import (
    deduplicate_by_rule,
    add_column_comments,
    write_silver
)

# COMMAND ----------

current_run_id = get_run_id()

# Leitura das tabelas Silver (clean)
df_customer        = spark.table("adventure_works_catalog.silver.clean_sales_customer")
df_sales_territory = spark.table("adventure_works_catalog.silver.clean_sales_territory")
df_sales           = spark.table("adventure_works_catalog.silver.clean_sales_order_header")
df_person          = spark.table("adventure_works_catalog.silver.clean_person")
df_store           = spark.table("adventure_works_catalog.silver.clean_sales_store")
df_inventory       = spark.table("adventure_works_catalog.silver.clean_production_inventory")
df_person_address  = spark.table("adventure_works_catalog.silver.clean_person_address")
df_vendor          = spark.table("adventure_works_catalog.silver.clean_purchasing_vendor")
df_product         = spark.table("adventure_works_catalog.silver.clean_production")
df_currency        = spark.table("adventure_works_catalog.silver.clean_sales_currency")
df_currency_rate   = spark.table("adventure_works_catalog.silver.clean_sales_currency_rate")

# COMMAND ----------

# =====================================================
# DIM_CURRENCY — SILVER 
# =====================================================
start_time = datetime.now()

# Granularidade: 1 linha por moedas e data de cotação
# Criando a tabela
spark.sql("""
CREATE TABLE IF NOT EXISTS adventure_works_catalog.silver.dim_currency (
    Currency_SK BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CurrencyRateID INT,
    FromCurrencyCode STRING,
    FromCurrencyName STRING,
    ToCurrencyCode STRING,
    ToCurrencyName STRING,
    CurrencyRateDate DATE,
    AverageRate DECIMAL(18,6),
    EndOfDayRate DECIMAL(18,6)
)
""")

# Registro para dados nulos
spark.sql("""
INSERT INTO adventure_works_catalog.silver.dim_currency
SELECT
    -1 AS Currency_SK,
    -1 AS CurrencyRateID,
    'UNK' AS FromCurrencyCode,
    'Not registered' AS FromCurrencyName,
    'UNK' AS ToCurrencyCode,
    'Not registered' AS ToCurrencyName,
    NULL AS CurrencyRateDate,
    0 AS AverageRate,
    0 AS EndOfDayRate
WHERE NOT EXISTS (
    SELECT 1
    FROM adventure_works_catalog.silver.dim_currency
    WHERE Currency_SK = -1
)
""")

# Preparação dos dados
df_dim_currency_base = (
    df_currency_rate.alias("cr")

    # Join moeda de origem
    .join(
        df_currency.alias("fc"),
        F.col("cr.FromCurrencyCode") == F.col("fc.CurrencyCode"),
        "left"
    )

    # Join moeda de destino
    .join(
        df_currency.alias("tc"),
        F.col("cr.ToCurrencyCode") == F.col("tc.CurrencyCode"),
        "left"
    )

    .select(
        F.col("cr.CurrencyRateID"),
        F.col("cr.FromCurrencyCode"),
        F.coalesce(F.col("fc.CurrencyName"), F.lit("Not registered")).alias("FromCurrencyName"),
        F.col("cr.ToCurrencyCode"),
        F.coalesce(F.col("tc.CurrencyName"), F.lit("Not registered")).alias("ToCurrencyName"),
        F.col("cr.CurrencyRateDate"),
        F.col("cr.AverageRate"),
        F.col("cr.EndOfDayRate")
)
)

# Garantia de Integridade
df_dim_currency_base = (
    df_dim_currency_base
    .filter(
        F.col("FromCurrencyCode").isNotNull() &
        F.col("ToCurrencyCode").isNotNull() &
        F.col("CurrencyRateDate").isNotNull()
    )
)

full_table_name = "adventure_works_catalog.silver.dim_currency"
table_name_short = "dim_currency"

try:
    df_dim_currency_base = deduplicate_by_rule(
        df_dim_currency_base,
        partition_cols=[
            "FromCurrencyCode",
            "ToCurrencyCode",
            "CurrencyRateDate"
        ],
        order_cols=[
            F.col("EndOfDayRate").desc(),
            F.col("CurrencyRateID").desc()
        ]
    )

    df_dim_currency_base.cache()

    #Registros processados após as regras e joins (volume transformado)
    rows_processed = df_dim_currency_base.count()

    silver_selection(
        spark=spark,
        run_id=current_run_id,
        df_input=df_dim_currency_base,
        process_name="Criação_dim_table",
        table_name=table_name_short
    )

    # Merge SCD Type 1
    df_dim_currency_base.createOrReplaceTempView("src_dim_currency")

    spark.sql("""
    MERGE INTO adventure_works_catalog.silver.dim_currency tgt
    USING src_dim_currency src
    ON tgt.FromCurrencyCode  = src.FromCurrencyCode
    AND tgt.ToCurrencyCode   = src.ToCurrencyCode
    AND tgt.CurrencyRateDate = src.CurrencyRateDate

    WHEN MATCHED AND (
        NOT (tgt.AverageRate   <=> src.AverageRate) OR
        NOT (tgt.EndOfDayRate  <=> src.EndOfDayRate) OR
        NOT (tgt.CurrencyRateID <=> src.CurrencyRateID) OR
        NOT (tgt.FromCurrencyName <=> src.FromCurrencyName) OR
        NOT (tgt.ToCurrencyName   <=> src.ToCurrencyName)
    )
    THEN UPDATE SET
        tgt.CurrencyRateID    = src.CurrencyRateID,
        tgt.FromCurrencyName  = src.FromCurrencyName,
        tgt.ToCurrencyName    = src.ToCurrencyName,
        tgt.AverageRate       = src.AverageRate,
        tgt.EndOfDayRate      = src.EndOfDayRate

    WHEN NOT MATCHED THEN
    INSERT (
        CurrencyRateID,
        FromCurrencyCode,
        FromCurrencyName,
        ToCurrencyCode,
        ToCurrencyName,
        CurrencyRateDate,
        AverageRate,
        EndOfDayRate
    )
    VALUES (
        src.CurrencyRateID,
        src.FromCurrencyCode,
        src.FromCurrencyName,
        src.ToCurrencyCode,
        src.ToCurrencyName,
        src.CurrencyRateDate,
        src.AverageRate,
        src.EndOfDayRate
    )
    """)

    #Pegar métricas do merge do DESCRIBE_HISTORY
    merge_metrics = (
        spark.sql(f"DESCRIBE HISTORY {full_table_name}")
        .orderBy(F.col("version").desc())
        .limit(1)
        .select("operationMetrics")
        .collect()[0]["operationMetrics"]
    )

    rows_written = (
        int(merge_metrics.get("numTargetRowsInserted", 0))
        + int(merge_metrics.get("numTargetRowsUpdated", 0))
    )

    audit_registration(
        spark=spark,
        run_id=current_run_id,
        process_name="Criação_dim_table",
        layer="SILVER",
        table_saved = table_name_short,
        start_date = start_time,
        rows_readed_batch = rows_processed,
        rows_written_batch = rows_written
    )

    df_dim_currency_base.unpersist()
    

except Exception as e:
    
    df_dim_currency_base.unpersist()

    audit_registration(
        spark=spark,
        run_id=current_run_id,
        process_name="Criação_dim_table",
        layer="SILVER",
        table_saved = table_name_short,
        start_date = start_time,
        status = "FAIL",
        error_msg = str(e)
    )

    print(f"Erro em {table_name_short}: {e}")
    

# Descrição das colunas
dim_currency_columns = {
    "Currency_SK": "Chave substituta da taxa de câmbio",
    "CurrencyRateID": "Identificador natural da taxa de câmbio",
    "FromCurrencyCode": "Código da moeda de origem",
    "FromCurrencyName": "Nome da moeda de origem",
    "ToCurrencyCode": "Código da moeda de destino",
    "ToCurrencyName": "Nome da moeda de destino",
    "CurrencyRateDate": "Data de vigência da taxa de câmbio",
    "AverageRate": "Taxa média de conversão entre as moedas",
    "EndOfDayRate": "Taxa de conversão registrada ao final do dia"
}

# Adicionando os comentários no Unity Catalog
add_column_comments(
    catalog="adventure_works_catalog",
    schema="silver",
    table="dim_currency",
    columns_dict=dim_currency_columns
)


