# Databricks notebook source
# MAGIC %md
# MAGIC # Dimensional Model – Dimensions
# MAGIC
# MAGIC Notebook responsável pela criação das **dimensões analíticas** do modelo dimensional (Adventure Works)
# MAGIC
# MAGIC Inclui dimensões com **chaves substitutas** e documentação no Unity Catalog.

# COMMAND ----------

import sys
sys.path.append("..")

# COMMAND ----------

#Imports e setup

from pyspark.sql import functions as F
from pyspark.sql import SparkSession
from pyspark.sql.functions import xxhash64
from datetime import datetime
from ADB.Module.SilverUtils import (
    deduplicate_by_rule,
    add_column_comments,
    write_silver,
)

# COMMAND ----------

# Leitura das tabelas 
df_sales_territory = spark.table("adventure_works_catalog.silver.clean_sales_territory")

# COMMAND ----------

# Criação da tabela
spark.sql("""
CREATE TABLE IF NOT EXISTS adventure_works_catalog.silver.dim_territory (
    Territory_SK BIGINT GENERATED BY DEFAULT AS IDENTITY,
    TerritoryID INT,
    TerritoryName STRING,
    TerritoryGroup STRING,
    CountryRegionCode STRING
)
""")

# Registros para dados nulos
spark.sql("""
INSERT INTO adventure_works_catalog.silver.dim_territory
SELECT
    -1 AS Territory_SK,
    -1 AS TerritoryID,
    'Not registered' AS TerritoryName,
    'Not registered' AS TerritoryGroup,
    'Not registered' AS CountryRegionCode
WHERE NOT EXISTS (
    SELECT 1
    FROM adventure_works_catalog.silver.dim_territory
    WHERE Territory_SK = -1
)
""")

# Preparação dos dados
df_dim_territory_base = (
    df_sales_territory
    .select(
        "TerritoryID",
        "TerritoryName",
        "TerritoryGroup",
        "CountryRegionCode"
    )
    .filter(F.col("TerritoryID").isNotNull())
)

# Garantia de integridade
df_dim_territory_base = deduplicate_by_rule(
    df_dim_territory_base,
    partition_cols=["TerritoryID"],
    order_cols=[
        F.col("TerritoryName").isNotNull().desc(),
        F.col("TerritoryGroup").isNotNull().desc()
    ]
)

# View de origem
df_dim_territory_base.createOrReplaceTempView("src_dim_territory")

# Merge SCD type 1
spark.sql("""
MERGE INTO adventure_works_catalog.silver.dim_territory tgt
USING src_dim_territory src
ON tgt.TerritoryID = src.TerritoryID

WHEN MATCHED AND (
    NOT (tgt.TerritoryName       <=> src.TerritoryName) OR
    NOT (tgt.TerritoryGroup      <=> src.TerritoryGroup) OR
    NOT (tgt.CountryRegionCode   <=> src.CountryRegionCode)
)
THEN UPDATE SET
    tgt.TerritoryName     = src.TerritoryName,
    tgt.TerritoryGroup    = src.TerritoryGroup,
    tgt.CountryRegionCode = src.CountryRegionCode

WHEN NOT MATCHED THEN
  INSERT (
    TerritoryID,
    TerritoryName,
    TerritoryGroup,
    CountryRegionCode
  )
  VALUES (
    src.TerritoryID,
    src.TerritoryName,
    src.TerritoryGroup,
    src.CountryRegionCode
  )
""")

# Descrição das colunas
dim_territory_columns = {
    "Territory_SK": "Chave substituta do território de vendas (surrogate key)",
    "TerritoryID": "Chave natural do território de vendas, proveniente da tabela SalesTerritory",
    "TerritoryName": "Nome descritivo do território de vendas",
    "TerritoryGroup": "Grupo geográfico ao qual o território pertence (ex: North America, Europe)",
    "CountryRegionCode": "Código do país ou região associado ao território"
}

# Aplicando os comentários no Unity Catalog
add_column_comments(
    catalog="adventure_works_catalog",
    schema="silver",
    table="dim_territory",
    columns_dict=dim_territory_columns
)

