# Databricks notebook source
# MAGIC %md
# MAGIC # Dimensional Model – Dimensions
# MAGIC
# MAGIC Notebook responsável pela criação das **dimensões analíticas** do modelo dimensional (Adventure Works)
# MAGIC
# MAGIC Inclui dimensões com **chaves substitutas** e documentação no Unity Catalog.

# COMMAND ----------

import sys
sys.path.append("..")

# COMMAND ----------

#Imports e setup

from pyspark.sql import functions as F
from pyspark.sql import SparkSession
from pyspark.sql.functions import xxhash64
from datetime import datetime
from ADB.Module.GovernanceUtils import audit_registration, get_run_id, silver_selection
from ADB.Module.SilverUtils import (
    deduplicate_by_rule,
    add_column_comments,
    write_silver
)

# COMMAND ----------

current_run_id = get_run_id()

# Leitura das tabelas Silver (clean)
df_customer        = spark.table("adventure_works_catalog.silver.clean_sales_customer")
df_sales_territory = spark.table("adventure_works_catalog.silver.clean_sales_territory")
df_sales           = spark.table("adventure_works_catalog.silver.clean_sales_order_header")
df_person          = spark.table("adventure_works_catalog.silver.clean_person")
df_store           = spark.table("adventure_works_catalog.silver.clean_sales_store")
df_inventory       = spark.table("adventure_works_catalog.silver.clean_production_inventory")
df_person_address  = spark.table("adventure_works_catalog.silver.clean_person_address")
df_vendor          = spark.table("adventure_works_catalog.silver.clean_purchasing_vendor")
df_product         = spark.table("adventure_works_catalog.silver.clean_production")
df_currency        = spark.table("adventure_works_catalog.silver.clean_sales_currency")
df_currency_rate   = spark.table("adventure_works_catalog.silver.clean_sales_currency_rate")

# COMMAND ----------

# =====================================================
# DIM_SUPPLIER - SILVER
# =====================================================
start_time = datetime.now()

# Granularidade: 1 linha por fornecedor

# Criando a tabela
spark.sql("""
CREATE TABLE IF NOT EXISTS adventure_works_catalog.silver.dim_supplier (
    Supplier_SK BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SupplierID INT,
    SupplierName STRING,
    CreditRating INT,
    IsActiveSupplier BOOLEAN
)
""")

# Registro para dados nulos
spark.sql("""
INSERT INTO adventure_works_catalog.silver.dim_supplier
SELECT
    -1 AS Supplier_SK,
    -1 AS SupplierID,
    'Not registered' AS SupplierName,
    NULL AS CreditRating,
    FALSE AS IsActiveSupplier
WHERE NOT EXISTS (
    SELECT 1
    FROM adventure_works_catalog.silver.dim_supplier
    WHERE Supplier_SK = -1
)
""")


# Preparação dos dados
df_dim_supplier_base = (
      df_vendor
    .select(
        # Chave natural
        F.col("VendorID").alias("SupplierID"),
        F.coalesce(F.col("VendorName"), F.lit("Not registered")).alias("SupplierName"),
        F.col("CreditRating"),
        F.coalesce(F.col("ActiveFlag"), F.lit(False)).alias("IsActiveSupplier")
    )
)

# Garantia de Integridade
df_dim_supplier_base = (
    df_dim_supplier_base
    .filter(F.col("SupplierID").isNotNull())
)

full_table_name = "adventure_works_catalog.silver.dim_supplier"
table_name_short ="dim_supplier"

try:
    df_dim_supplier_base = deduplicate_by_rule(
        df_dim_supplier_base,
        partition_cols=["SupplierID"],
        order_cols=[
            F.col("IsActiveSupplier").desc(),
            F.col("CreditRating").desc()
        ]
    )
    
    df_dim_supplier_base.cache()

    #Registros processados após as regras e joins (volume transformado)
    rows_processed = df_dim_supplier_base.count()

    silver_selection(
        spark=spark,
        run_id=current_run_id,
        df_input=df_dim_supplier_base,
        process_name="Criação_dim_table",
        table_name=table_name_short
    )

    # Merge SCD Type 1
    df_dim_supplier_base.createOrReplaceTempView("src_dim_supplier")

    spark.sql("""
    MERGE INTO adventure_works_catalog.silver.dim_supplier tgt
    USING src_dim_supplier src
    ON tgt.SupplierID = src.SupplierID

    WHEN MATCHED AND (
        NOT (tgt.SupplierName    <=> src.SupplierName) OR
        NOT (tgt.CreditRating    <=> src.CreditRating) OR
        NOT (tgt.IsActiveSupplier <=> src.IsActiveSupplier)
    )
    THEN UPDATE SET
        tgt.SupplierName     = src.SupplierName,
        tgt.CreditRating     = src.CreditRating,
        tgt.IsActiveSupplier = src.IsActiveSupplier

    WHEN NOT MATCHED THEN
    INSERT (
        SupplierID,
        SupplierName,
        CreditRating,
        IsActiveSupplier
    )
    VALUES (
        src.SupplierID,
        src.SupplierName,
        src.CreditRating,
        src.IsActiveSupplier
    )
    """)


    #Pegar métricas do merge do DESCRIBE_HISTORY
    merge_metrics = (
        spark.sql(f"DESCRIBE HISTORY {full_table_name}")
        .orderBy(F.col("version").desc())
        .limit(1)
        .select("operationMetrics")
        .collect()[0]["operationMetrics"]
    )

    rows_written = (
        int(merge_metrics.get("numTargetRowsInserted", 0))
        + int(merge_metrics.get("numTargetRowsUpdated", 0))
    )

    audit_registration(
        spark=spark,
        run_id=current_run_id,
        process_name="Criação_dim_table",
        layer="SILVER",
        table_saved = table_name_short,
        start_date = start_time,
        rows_readed_batch = rows_processed,
        rows_written_batch = rows_written
    )

    df_dim_supplier_base.unpersist()

except Exception as e:

    df_dim_supplier_base.unpersist()
    
    audit_registration(
        spark=spark,
        run_id=current_run_id,
        process_name="Criação_dim_table",
        layer="SILVER",
        table_saved = table_name_short,
        start_date = start_time,
        status = "FAIL",
        error_msg = str(e)
    )

    print(f"Erro em dim_supplier: {e}")

# Descrição das colunas
dim_supplier_columns = {
    "Supplier_SK": "Chave substituta do fornecedor",
    "SupplierID": "Identificador natural do fornecedor",
    "SupplierName": "Nome do fornecedor",
    "CreditRating": "Classificação de crédito do fornecedor",
    "IsActiveSupplier": "Indicador se o fornecedor está ativo"
}

# Adicionando comentários no Unity Catalog
add_column_comments(
    catalog="adventure_works_catalog",
    schema="silver",
    table="dim_supplier",
    columns_dict=dim_supplier_columns
)
