# Databricks notebook source
# MAGIC %md
# MAGIC # Dimensional Model – Dimensions
# MAGIC
# MAGIC Notebook responsável pela criação das **dimensões analíticas** do modelo dimensional (Adventure Works)
# MAGIC
# MAGIC Inclui dimensões com **chaves substitutas** e documentação no Unity Catalog.

# COMMAND ----------

import sys
sys.path.append("..")

# COMMAND ----------

#Imports e setup

from pyspark.sql import functions as F
from pyspark.sql import SparkSession
from pyspark.sql.functions import xxhash64
from datetime import datetime
from ADB.Module.SilverUtils import (
    deduplicate_by_rule,
    add_column_comments,
    write_silver,
)

# COMMAND ----------

# Leitura das tabelas Silver (clean)
df_customer        = spark.table("adventure_works_catalog.silver.clean_sales_customer")
df_sales_territory = spark.table("adventure_works_catalog.silver.clean_sales_territory")
df_sales           = spark.table("adventure_works_catalog.silver.clean_sales_order_header")
df_person          = spark.table("adventure_works_catalog.silver.clean_person")
df_store           = spark.table("adventure_works_catalog.silver.clean_sales_store")
df_inventory       = spark.table("adventure_works_catalog.silver.clean_production_inventory")
df_person_address  = spark.table("adventure_works_catalog.silver.clean_person_address")
df_vendor          = spark.table("adventure_works_catalog.silver.clean_purchasing_vendor")
df_product         = spark.table("adventure_works_catalog.silver.clean_production")
df_currency        = spark.table("adventure_works_catalog.silver.clean_sales_currency")
df_currency_rate   = spark.table("adventure_works_catalog.silver.clean_sales_currency_rate")

# COMMAND ----------

# =====================================================
# DIM_LOCATION - SILVER
# =====================================================
# Granularidade: 1 linha por AddressID

# Criando a tabela
spark.sql("""
CREATE TABLE IF NOT EXISTS adventure_works_catalog.silver.dim_location (
    Location_SK BIGINT GENERATED BY DEFAULT AS IDENTITY,
    AddressID INT,
    AddressLine1 STRING,
    AddressLine2 STRING,
    City STRING,
    StateProvinceName STRING,
    CountryName STRING,
    PostalCode STRING,
    SpatialLocation STRING
)
""")

# Registro para dados nulos
spark.sql("""
INSERT INTO adventure_works_catalog.silver.dim_location
SELECT
    -1 AS Location_SK,
    -1 AS AddressID,
    'Not registered' AS AddressLine1,
    NULL AS AddressLine2,
    'Not registered' AS City,
    'Not registered' AS StateProvinceName,
    'Not registered' AS CountryName,
    'Not registered' AS PostalCode,
    NULL AS SpatialLocation
WHERE NOT EXISTS (
    SELECT 1
    FROM adventure_works_catalog.silver.dim_location
    WHERE Location_SK = -1
)
""")

# Preparação dos dados
df_dim_location_base = (
    df_person_address
    .select(
        F.col("AddressID"),

        F.coalesce(F.col("AddressLine1"), F.lit("Not registered")).alias("AddressLine1"),
        F.col("AddressLine2"),  
        F.coalesce(F.col("City"), F.lit("Not registered")).alias("City"),
        F.coalesce(F.col("StateProvinceName"), F.lit("Not registered")).alias("StateProvinceName"),
        F.coalesce(F.col("CountryName"), F.lit("Not registered")).alias("CountryName"),
        F.coalesce(F.col("PostalCode"), F.lit("Not registered")).alias("PostalCode"),
        F.col("SpatialLocation")
    )
)

# Garantia de Integridade 
df_dim_location_base = (
    df_dim_location_base
    .filter(F.col("AddressID").isNotNull())
)

df_dim_location_base = deduplicate_by_rule(
    df_dim_location_base,
    partition_cols=["AddressID"],
    order_cols=[
        F.col("AddressLine1").isNotNull().desc(),
        F.col("City").isNotNull().desc(),
        F.col("PostalCode").isNotNull().desc()
    ]
)

# View de origem
df_dim_location_base.createOrReplaceTempView("src_dim_location")

# Merge SCD Type 1
spark.sql("""
MERGE INTO adventure_works_catalog.silver.dim_location tgt
USING src_dim_location src
ON tgt.AddressID = src.AddressID

WHEN MATCHED AND (
    NOT (tgt.AddressLine1       <=> src.AddressLine1) OR
    NOT (tgt.AddressLine2       <=> src.AddressLine2) OR
    NOT (tgt.City               <=> src.City) OR
    NOT (tgt.StateProvinceName  <=> src.StateProvinceName) OR
    NOT (tgt.CountryName        <=> src.CountryName) OR
    NOT (tgt.PostalCode         <=> src.PostalCode) OR
    NOT (tgt.SpatialLocation    <=> src.SpatialLocation)
)
THEN UPDATE SET
    tgt.AddressLine1      = src.AddressLine1,
    tgt.AddressLine2      = src.AddressLine2,
    tgt.City              = src.City,
    tgt.StateProvinceName = src.StateProvinceName,
    tgt.CountryName       = src.CountryName,
    tgt.PostalCode        = src.PostalCode,
    tgt.SpatialLocation   = src.SpatialLocation

WHEN NOT MATCHED THEN
  INSERT (
    AddressID,
    AddressLine1,
    AddressLine2,
    City,
    StateProvinceName,
    CountryName,
    PostalCode,
    SpatialLocation
  )
  VALUES (
    src.AddressID,
    src.AddressLine1,
    src.AddressLine2,
    src.City,
    src.StateProvinceName,
    src.CountryName,
    src.PostalCode,
    src.SpatialLocation
  )
""")

# Descrição das colunas
dim_location_columns = {
    "Location_SK": "Chave substituta da localização (surrogate key)",
    "AddressID": "Chave natural do endereço, proveniente da tabela Address",
    "AddressLine1": "Primeira linha do endereço",
    "AddressLine2": "Segunda linha do endereço (complemento)",
    "City": "Cidade do endereço",
    "StateProvinceName": "Estado ou província do endereço",
    "CountryName": "País do endereço",
    "PostalCode": "Código postal do endereço",
    "SpatialLocation": "Informação espacial/geográfica do endereço"
}

# Aplicando os comentários no Unity Catalog
add_column_comments(
    catalog="adventure_works_catalog",
    schema="silver",
    table="dim_location",
    columns_dict=dim_location_columns
)
